name: Hardware Unit Tests
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  rtl-test-vlt:
    name: RTL test using verilator
    runs-on: ubuntu-22.04
    container:
      image: rgantonio/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Pull Snitch cluster files
        run: |
          bender script flist
      - name: Running Pytest
        run: |
          pytest -v -o log_cli=True

jobs:
  tpl-test-gen:
    name: Template generation test
    runs-on: ubuntu-22.04
    container:
      image: rgantonio/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Generate streamer SV template
        run: |
        python3 util/scripts/template_gen.py \
        --cfg_path="./util/cfg/streamer_cfg.hjson" \
        --tpl_path="./util/templates/streamer.sv.tpl" \
        --out_path="./rtl/streamer_wrapper.sv"
  

