name: Hello world workflow
on: [push, pull_request, workflow_dispatch]

jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"
        shell: bash