# ---------------------------------------------------------
# Copyright 2023 KULeuven
# Author: Ryan Antonio <ryan.antonio@esat.kuleuven.be>
# ---------------------------------------------------------

name: Hardware Tests
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  rtl-test-vlt:
    name: RTL test using verilator
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax-cocotb
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Pull Snitch cluster files
        run: |
          bender script flist
      - name: Running Pytest
        run: |
          pytest
