name: Hardware Unit Tests
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  rtl-test-vlt:
    name: RTL test using verilator
    runs-on: ubuntu-22.04
    container:
      image: rgantonio/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Running Pytest
        run: |
          pytest -v -o log_cli=True

  bender-test:
    name: Bender test
    runs-on: ubuntu-22.04
    container:
      image: rgantonio/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Bender test
        run: |
          bender script flist

