# ---------------------------------------------------------
# Copyright 2023 KULeuven
# Author: Ryan Antonio <ryan.antonio@esat.kuleuven.be>
# ---------------------------------------------------------

name: Hardware Tests
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  streamer-test-gen:
    name: Template generation test
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Generate SNAX streamer
        run: |
          make gen_stream_tb

  rtl-test-vlt:
    name: RTL test using verilator
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax-cocotb
    steps:
      - uses: actions/checkout@v3
      - name: Pull Snitch cluster files
        run: |
          bender script flist
      - name: Running Pytest
        run: |
          pytest -v -o log_cli=True
